// config/sunatUnits.ts
// Unidades de medida del portal SUNAT. Fuente de verdad del frontend.
// El texto debe coincidir EXACTAMENTE con las opciones de SUNAT: el backend-sunat
// lo escribe tal cual en el ComboBox durante la emisión.
export const SUNAT_UNITS = [
  'UNIDAD',
  'KILOGRAMO',
  'CAJA',
  'PAQUETE',
  'TONELADAS',
  'BALDE',
  'BARRILES',
  'BOBINAS',
  'BOLSA',
  'BOTELLAS',
  'CARTONES',
  'CENTIMETRO CUADRADO',
  'CENTIMETRO CUBICO',
  'CENTIMETRO LINEAL',
  'CIENTO DE UNIDADES',
  'CILINDRO',
  'CONOS',
  'DOCENA',
  'DOCENA POR 10**6',
  'FARDO',
  'GALON INGLES (4,545956L)',
  'GRAMO',
  'GRUESA',
  'HECTOLITRO',
  'HOJA',
  'JUEGO',
  'KILOMETRO',
  'KILOVATIO HORA',
  'KIT',
  'LATAS',
  'LIBRAS',
  'LITRO',
  'MEGAWATT HORA',
  'METRO',
  'METRO CUADRADO',
  'METRO CUBICO',
  'MILIGRAMOS',
  'MILILITRO',
  'MILIMETRO',
  'MILIMETRO CUADRADO',
  'MILIMETRO CUBICO',
  'MILLARES',
  'MILLON DE UNIDADES',
  'ONZAS',
  'PALETAS',
  'PAR',
  'PIE TABLAR',
  'PIES',
  'PIES CUADRADOS',
  'PIES CUBICOS',
  'PIEZAS',
  'PLACAS',
  'PLIEGO',
  'PULGADAS',
  'RESMA',
  'TAMBOR',
  'TONELADA CORTA',
  'TONELADA LARGA',
  'TUBOS',
  'US GALON (3,7843 L)',
  'YARDA',
  'YARDA CUADRADA',
] as const;

export type UnitOfMeasure = (typeof SUNAT_UNITS)[number];

const SUNAT_UNITS_SET: ReadonlySet<string> = new Set(SUNAT_UNITS);

export const isSunatUnit = (value: string): value is UnitOfMeasure =>
  SUNAT_UNITS_SET.has(value);
